### PR TITLE
Formatting

### PR DESCRIPTION
**Pull request by m417z**
Depends on https://github.com/samoylenko/service/pull/2

### CODE REVIEW

**Comment by samoylenko** [comment]
Just wanted to say that was my old old coding style, and I am glad you took time to fix it. Fully agree with the proposed change.

Thank you again for your contributions Michael

**Comment by samoylenko** [comment]
My understanding, this requires rebasing now that the fix was merged in a separate PR, and the old fix commit remains in this branch?

**Comment by m417z** [comment]
I'm not sure that was necessary, but in any case I rebased.

**Comment by samoylenko** [comment]
Thank you. That helped - i saw 2 commits in this PR, now I see only one, with formatting.

**Comment by m417z** [comment]
You're welcome :)
P.S. FYI, your domain, `security.needs.software`, has an invalid certificate. The http version works.

**Comment by samoylenko** [comment]
Thanks :) they require to create a website with redirect to allow for automatic cert updates. I forgot to do  that. adding to my long-long TODO list

**Pull request merged**
