### PR TITLE
Fixed to allow compiling in VS 2017

### PR DESCRIPTION
**Pull request by m417z**

### CODE REVIEW

**Comment by samoylenko** [comment]
Very impressive! Thank you so much! I need to quickly research why you had to change items like `DWORD` to `int` - i just remember that when I was writing this code 10 years ago, I followed MSDN and it had to change it the opposite way (from `int` to `DWORD`). So if you have a link / thoughts on this topic, please let me know. But I am not planning to take too long anyways

**Comment by m417z** [comment]
I don't remember either (I changed the code a while ago). `DWORD` makes sense due to [this](https://docs.microsoft.com/en-us/windows/desktop/api/winsvc/nc-winsvc-lpservice_main_functiona). I probably didn't bother to check since I just wanted a working code for a test, and since main's `argc` is of the type `int`. I'll revert this change.

**Comment by samoylenko** [comment]
> I don't remember either (I changed the code a while ago). `DWORD` makes sense due to [this](https://docs.microsoft.com/en-us/windows/desktop/api/winsvc/nc-winsvc-lpservice_main_functiona). I probably didn't bother to check since I just wanted a working code for a test, and since main's `argc` is of the type `int`. I'll revert this change.

Your quick response is very appreciated - sorry I need time to catch up. Your code looks good - and its just me trying to verify the proposed changes. Are you sure you don't want me to put a reference to your repo with updated version of the code instead of changing my outdated code?

**Comment by m417z** [comment]
Updated both branches, reverting the `DWORD` change. Now there're even less changes, and I verified that it compiles without errors or warnings.

> Are you sure you don't want me to put a reference to your repo with updated version of the code instead of changing my outdated code?

That's a minor update so I don't think that it's worth it. You can also reject the formatting pull request if you prefer, I don't really mind.

**Comment by samoylenko** [comment]
You've added a lot of value, and its highly appreciated. I will accept both your requests.
Thank you for this.

**Pull request merged**
